services:
  init:
    build: .
    container_name: mctiny-init
    command: kemtls-initialise
    volumes:
      - ./state:/app/state
    working_dir: /app


  server:
    build: .
    container_name: mctiny-server
    command: kemtls-server
    depends_on:
      init:
        condition: service_completed_successfully
    volumes:
      - ./state:/app/state
    ports:
      - "4433:4433"
    networks:
      - mctiny-net

  client:
    build: .
    container_name: mctiny-client
    # delay start slightly to ensure server socket is open
    command: sh -c "sleep 2 && kemtls-client"
    depends_on:
      server:
        condition: service_started
    volumes:
      - ./state:/app/state
    networks:
      - mctiny-net

networks:
  mctiny-net: